DROP TABLE IF EXISTS TODO;
CREATE TABLE TODO (
    IDX INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    CONTENT VARCHAR(255) NOT NULL,
    DONE_YN CHAR(1) NOT NULL DEFAULT 'N',
    DELETE_YN CHAR(1) NOT NULL DEFAULT 'N',
    CREATED_DATE TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP(),
    MODIFIED_DATE TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP()
);